// Theme system. Each theme maps semantic role names to style objects
// { fg?, bg?, bold?, dim?, underline?, inverse? } that screen.mjs understands.
// Legacy string values are still supported for backward compat.

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { THEME_FILE } from './config.mjs';

const THEMES = {
  default: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'white', bold: true },
    dim: { dim: true },
    accent: { fg: 'cyan' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'yellow' },
    pr: { fg: 'cyan' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'cyan' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'white', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'cyan', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'cyan' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'yellow' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'white', bold: true, underline: true },
    inputBox: { fg: 'cyan', underline: true },
  },
  highContrast: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'white', bold: true, underline: true },
    dim: { fg: 'gray' },
    accent: { fg: 'white', bold: true },
    star: { fg: 'yellow', bold: true },
    fork: { fg: 'cyan', bold: true },
    issue: { fg: 'yellow', bold: true },
    pr: { fg: 'cyan', bold: true },
    release: { fg: 'green', bold: true },
    success: { fg: 'green', bold: true },
    warning: { fg: 'yellow', bold: true },
    error: { fg: 'red', bold: true },
    info: { fg: 'cyan', bold: true },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'white', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'cyan', fg: 'darkGray', bold: true },
    chipInactive: { fg: 'gray' },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'cyan', bold: true },
    activity: { fg: 'green', bold: true },
    trending: { fg: 'magenta', bold: true },
    unread: { fg: 'yellow', bold: true },
    muted: { fg: 'gray' },
    tabBar: { fg: 'gray' },
    tabBarActive: { fg: 'white', bold: true, underline: true },
    inputBox: { fg: 'white', bold: true, underline: true },
  },
  dracula: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'magenta', bold: true },
    dim: { dim: true },
    accent: { fg: 'magenta' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'magenta' },
    pr: { fg: 'green' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'cyan' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'magenta', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'magenta', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'magenta' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'magenta' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'magenta', bold: true, underline: true },
    inputBox: { fg: 'magenta', underline: true },
  },
  solarized: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'yellow', bold: true },
    dim: { dim: true },
    accent: { fg: 'blue' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'yellow' },
    pr: { fg: 'blue' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'blue' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'yellow', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'blue', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'blue' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'yellow' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'yellow', bold: true, underline: true },
    inputBox: { fg: 'blue', underline: true },
  },
  nord: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'cyan', bold: true },
    dim: { dim: true },
    accent: { fg: 'cyan' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'yellow' },
    pr: { fg: 'cyan' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'cyan' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'cyan', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'cyan', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'cyan' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'yellow' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'cyan', bold: true, underline: true },
    inputBox: { fg: 'cyan', underline: true },
  },
  monokai: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'green', bold: true },
    dim: { dim: true },
    accent: { fg: 'yellow' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'yellow' },
    pr: { fg: 'magenta' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'cyan' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'green', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'yellow', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'magenta' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'yellow' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'yellow', bold: true, underline: true },
    inputBox: { fg: 'yellow', underline: true },
  },
  gruvbox: {
    title: { fg: 'white', bold: true },
    heading: { fg: 'yellow', bold: true },
    dim: { dim: true },
    accent: { fg: 'cyan' },
    star: { fg: 'yellow' },
    fork: { fg: 'cyan' },
    issue: { fg: 'red' },
    pr: { fg: 'green' },
    release: { fg: 'green' },
    success: { fg: 'green' },
    warning: { fg: 'yellow' },
    error: { fg: 'red' },
    info: { fg: 'cyan' },
    selection: { bg: 'blue', fg: 'white', bold: true },
    selectionDim: { bg: 'darkGray', fg: 'white' },
    header: { fg: 'yellow', bold: true, underline: true },
    statusBar: { bg: 'darkGray', fg: 'white' },
    chipActive: { bg: 'yellow', fg: 'darkGray', bold: true },
    chipInactive: { dim: true },
    modalBackdrop: { bg: 'darkGray' },
    languageBar: { fg: 'cyan' },
    activity: { fg: 'green' },
    trending: { fg: 'magenta' },
    unread: { fg: 'yellow' },
    muted: { dim: true },
    tabBar: { dim: true },
    tabBarActive: { fg: 'yellow', bold: true, underline: true },
    inputBox: { fg: 'yellow', underline: true },
  },
};

let active = 'default';

export function listThemes() { return Object.keys(THEMES); }
export function getThemeName() { return active; }

export function setTheme(name) {
  if (!THEMES[name]) return false;
  active = name;
  try { writeFileSync(THEME_FILE, name); } catch {}
  return true;
}

export function loadTheme() {
  try {
    if (existsSync(THEME_FILE)) {
      const name = readFileSync(THEME_FILE, 'utf-8').trim();
      if (THEMES[name]) active = name;
    }
  } catch {}
  return active;
}

// Resolve a semantic role → style value.
// Returns object { fg?, bg?, bold?, ... } if the theme entry is an object,
// or a legacy string if it's a string. Both work with screen.mjs.
export function color(role) {
  return THEMES[active][role] ?? null;
}
