// Theme system — fully distinct palettes for every theme.
// Each theme maps semantic role names to style objects understood by screen.mjs.
//
// Color values accepted by screen.mjs:
//   'cyan'        → named ANSI-8 color (always works)
//   '#rrggbb'     → true-color hex  (falls back to 256-color on non-truecolor terminals)
//   [r, g, b]     → true-color tuple
//   '256:n'       → explicit xterm-256 index
//
// Themes are designed so they look distinctly different from each other:
//   default      — professional dark teal/cyan on near-black
//   highContrast — maximum legibility, bold everything, bright whites
//   dracula      — purple/pink/green on deep charcoal
//   solarized    — muted teal/orange on warm beige-grey
//   nord         — icy blue/frost on dark navy
//   monokai      — vivid yellow/pink/green on dark background
//   gruvbox      — warm earth tones, gold/orange/green on brown-black
//   light        — dark text on bright white for daylight use
//   ayu          — deep blue/orange IDE palette, popular in VS Code
//   catppuccin   — soft pastel lavender/pink/blue on dark slate

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { NO_COLOR } from './config.mjs';
import { THEME_FILE } from './config.mjs';
import { appState } from './state.mjs';

// ── Palette constants ──────────────────────────────────────────────
// Named so themes read like a design spec, not a wall of hex codes.

const P = {
  // default — GitHub-inspired dark
  d_bg:      '#0d1117',
  d_fg:      '#e6edf3',
  d_fgDim:   '#8b949e',
  d_accent:  '#58a6ff',  // blue link
  d_green:   '#3fb950',
  d_yellow:  '#d29922',
  d_red:     '#f85149',
  d_orange:  '#e3b341',
  d_purple:  '#bc8cff',
  d_teal:    '#39d3c3',
  d_chrome:  '#161b22',
  d_sel:     '#1f6feb',

  // dracula
  dr_bg:     '#282a36',
  dr_chrome: '#21222c',
  dr_fg:     '#f8f8f2',
  dr_purple: '#bd93f9',
  dr_pink:   '#ff79c6',
  dr_green:  '#50fa7b',
  dr_yellow: '#f1fa8c',
  dr_orange: '#ffb86c',
  dr_red:    '#ff5555',
  dr_cyan:   '#8be9fd',
  dr_comment:'#6272a4',
  dr_sel:    '#44475a',

  // solarized dark
  sol_base03: '#002b36',
  sol_base02: '#073642',
  sol_base01: '#586e75',
  sol_base00: '#657b83',
  sol_base0:  '#839496',
  sol_base1:  '#93a1a1',
  sol_base2:  '#eee8d5',
  sol_base3:  '#fdf6e3',
  sol_yellow: '#b58900',
  sol_orange: '#cb4b16',
  sol_red:    '#dc322f',
  sol_magenta:'#d33682',
  sol_violet: '#6c71c4',
  sol_blue:   '#268bd2',
  sol_cyan:   '#2aa198',
  sol_green:  '#859900',

  // nord
  nord0:  '#2e3440',
  nord1:  '#3b4252',
  nord2:  '#434c5e',
  nord3:  '#4c566a',
  nord4:  '#d8dee9',
  nord5:  '#e5e9f0',
  nord6:  '#eceff4',
  nord7:  '#8fbcbb',
  nord8:  '#88c0d0',
  nord9:  '#81a1c1',
  nord10: '#5e81ac',
  nord11: '#bf616a',
  nord12: '#d08770',
  nord13: '#ebcb8b',
  nord14: '#a3be8c',
  nord15: '#b48ead',

  // monokai
  mk_bg:     '#272822',
  mk_chrome: '#1e1f1c',
  mk_fg:     '#f8f8f2',
  mk_yellow: '#e6db74',
  mk_orange: '#fd971f',
  mk_red:    '#f92672',
  mk_purple: '#ae81ff',
  mk_blue:   '#66d9e8',
  mk_green:  '#a6e22e',
  mk_comment:'#75715e',
  mk_sel:    '#49483e',

  // gruvbox dark hard
  gb_bg0h:   '#1d2021',
  gb_bg0:    '#282828',
  gb_bg1:    '#3c3836',
  gb_bg2:    '#504945',
  gb_bg3:    '#665c54',
  gb_bg4:    '#7c6f64',
  gb_fg0:    '#fbf1c7',
  gb_fg1:    '#ebdbb2',
  gb_fg2:    '#d5c4a1',
  gb_fg3:    '#bdae93',
  gb_fg4:    '#a89984',
  gb_red:    '#cc241d',
  gb_redB:   '#fb4934',
  gb_green:  '#98971a',
  gb_greenB: '#b8bb26',
  gb_yellow: '#d79921',
  gb_yellowB:'#fabd2f',
  gb_blue:   '#458588',
  gb_blueB:  '#83a598',
  gb_purple: '#b16286',
  gb_purpleB:'#d3869b',
  gb_aqua:   '#689d6a',
  gb_aquaB:  '#8ec07c',
  gb_orange: '#d65d0e',
  gb_orangeB:'#fe8019',

  // light — bright, paper-like
  lt_bg:     '#ffffff',
  lt_bg2:    '#f6f8fa',
  lt_border: '#d0d7de',
  lt_fg:     '#1f2328',
  lt_fgDim:  '#6e7781',
  lt_blue:   '#0550ae',
  lt_green:  '#1a7f37',
  lt_red:    '#cf222e',
  lt_orange: '#953800',
  lt_purple: '#8250df',
  lt_teal:   '#0969da',
  lt_sel:    '#0550ae',

  // ayu dark
  ayu_bg:    '#0f1419',
  ayu_bg2:   '#1c2128',
  ayu_fg:    '#bfbdb6',
  ayu_fgDim: '#5c6773',
  ayu_orange:'#ff8f40',
  ayu_yellow:'#e6b450',
  ayu_green: '#7fd962',
  ayu_cyan:  '#39bae6',
  ayu_blue:  '#59c2ff',
  ayu_purple:'#d2a6ff',
  ayu_red:   '#ff3333',
  ayu_sel:   '#273747',
  ayu_ui:    '#1c2736',

  // catppuccin mocha
  cat_base:  '#1e1e2e',
  cat_mantle:'#181825',
  cat_crust: '#11111b',
  cat_text:  '#cdd6f4',
  cat_subtext1:'#bac2de',
  cat_subtext0:'#a6adc8',
  cat_overlay2:'#9399b2',
  cat_overlay1:'#7f849c',
  cat_surface2:'#585b70',
  cat_surface1:'#45475a',
  cat_surface0:'#313244',
  cat_rosewater:'#f5e0dc',
  cat_flamingo: '#f2cdcd',
  cat_pink:     '#f38ba8',
  cat_mauve:    '#cba6f7',
  cat_red:      '#f38ba8',
  cat_maroon:   '#eba0ac',
  cat_peach:    '#fab387',
  cat_yellow:   '#f9e2af',
  cat_green:    '#a6e3a1',
  cat_teal:     '#94e2d5',
  cat_sky:      '#89dceb',
  cat_sapphire: '#74c7ec',
  cat_blue:     '#89b4fa',
  cat_lavender: '#b4befe',
};

// ── Helper: build a full theme from a spec object ──────────────────
// Every key is a semantic role. Missing keys fall back to the default theme.
function makeTheme(spec) {
  return spec;
}

// ── Default — GitHub dark, professional ───────────────────────────
const DEFAULT = makeTheme({
  title:       { fg: P.d_fg,     bold: true },
  heading:     { fg: P.d_fg,     bold: true },
  dim:         { fg: P.d_fgDim },
  accent:      { fg: P.d_accent },
  star:        { fg: P.d_orange, bold: true },
  fork:        { fg: P.d_teal },
  issue:       { fg: P.d_yellow },
  pr:          { fg: P.d_accent },
  release:     { fg: P.d_green },
  success:     { fg: P.d_green },
  warning:     { fg: P.d_yellow },
  error:       { fg: P.d_red },
  info:        { fg: P.d_accent },
  selection:   { bg: P.d_sel,    fg: '#ffffff', bold: true },
  selectionDim:{ bg: '#21262d',  fg: P.d_fgDim },
  header:      { fg: P.d_fg,     bold: true, underline: true },
  statusBar:   { bg: P.d_chrome, fg: P.d_fgDim },
  chrome:      { bg: P.d_chrome, fg: P.d_fg },
  chromeAccent:{ bg: P.d_chrome, fg: P.d_accent, bold: true },
  tabInactive: { fg: P.d_fgDim },
  tabActive:   { bg: P.d_sel,    fg: '#ffffff', bold: true },
  tabActiveBg: { bg: P.d_sel,    fg: '#ffffff', bold: true },
  tabBadge:    { bg: P.d_orange, fg: '#000000', bold: true },
  chipActive:  { bg: P.d_sel,    fg: '#ffffff', bold: true },
  chipInactive:{ fg: P.d_fgDim },
  chipDismissible: { bg: '#21262d', fg: P.d_accent },
  modalBackdrop:   { bg: '#161b22' },
  modalBorder:     { fg: P.d_accent, bold: true },
  languageBar: { fg: P.d_teal },
  activity:    { fg: P.d_green },
  trending:    { fg: P.d_purple },
  unread:      { fg: P.d_orange, bold: true },
  muted:       { fg: P.d_fgDim },
  tabBar:      { fg: P.d_fgDim },
  tabBarActive:{ fg: P.d_accent, bold: true, underline: true },
  inputBox:    { bg: '#161b22',  fg: P.d_accent, underline: true },
  inputPrompt: { fg: P.d_accent, bold: true },
  cardLabel:   { fg: P.d_fgDim },
  cardValue:   { fg: P.d_fg,     bold: true },
  breadcrumb:  { fg: P.d_fgDim },
  breadcrumbSep:{ fg: '#30363d' },
  breadcrumbActive: { fg: P.d_accent, bold: true },
  welcomeTitle:{ fg: P.d_accent, bold: true },
  welcomeAccent:{ fg: P.d_orange },
  keyHint:     { fg: P.d_accent, bold: true },
  keyHintBracket:{ fg: P.d_fgDim },
  rateOk:      { fg: P.d_green },
  rateWarn:    { fg: P.d_yellow },
  rateCrit:    { fg: P.d_red },
  toastInfo:   { bg: '#1c2d3e', fg: P.d_accent, bold: true },
  toastSuccess:{ bg: '#1a2f1a', fg: P.d_green,  bold: true },
  toastError:  { bg: '#2d1a1a', fg: P.d_red,    bold: true },
  toastWarning:{ bg: '#2d2a1a', fg: P.d_yellow, bold: true },
  sectionHeading: { fg: P.d_accent, bold: true },
  repoName:    { fg: P.d_fg },
  repoNameSelected: { fg: P.d_accent, bold: true },
  statValue:   { fg: P.d_fg,     bold: true },
  date:        { fg: P.d_fgDim },
  packageName: { fg: P.d_fg },
  packageSize: { fg: P.d_fgDim },
  packageTag:  { fg: P.d_teal },
  downloadCount:{ fg: P.d_fgDim },
  pinned:      { fg: P.d_orange, bold: true },
  bookmarked:  { fg: P.d_purple },
  cardBorder:  { fg: '#30363d' },
  cardBorderFocused: { fg: P.d_accent, bold: true },
  listItem:    { fg: P.d_fg },
  listItemDim: { fg: P.d_fgDim },
  emptyIcon:   { fg: P.d_teal },
  emptyTitle:  { fg: P.d_fg,     bold: true },
  emptyMessage:{ fg: P.d_fgDim },
  heatmapLow:  { fg: '#0e4429' },
  heatmapMid:  { fg: '#26a641' },
  heatmapHigh: { fg: '#39d353', bold: true },
  traffic:     { fg: P.d_teal },
  milestone:   { fg: P.d_yellow },
  label:       { fg: P.d_purple },
});

// ── High Contrast — accessibility-first, bold everything ──────────
const HIGH_CONTRAST = makeTheme({
  title:       { fg: '#ffffff', bold: true },
  heading:     { fg: '#ffffff', bold: true, underline: true },
  dim:         { fg: '#aaaaaa' },
  accent:      { fg: '#00ffff', bold: true },
  star:        { fg: '#ffff00', bold: true },
  fork:        { fg: '#00ffff', bold: true },
  issue:       { fg: '#ffff00', bold: true },
  pr:          { fg: '#00ffff', bold: true },
  release:     { fg: '#00ff00', bold: true },
  success:     { fg: '#00ff00', bold: true },
  warning:     { fg: '#ffff00', bold: true },
  error:       { fg: '#ff4444', bold: true },
  info:        { fg: '#00ffff', bold: true },
  selection:   { bg: '#0000aa', fg: '#ffffff', bold: true },
  selectionDim:{ bg: '#333333', fg: '#ffffff' },
  header:      { fg: '#ffffff', bold: true, underline: true },
  statusBar:   { bg: '#000000', fg: '#ffffff' },
  chrome:      { bg: '#000000', fg: '#ffffff' },
  chromeAccent:{ bg: '#000000', fg: '#00ffff', bold: true },
  tabInactive: { fg: '#aaaaaa' },
  tabActive:   { bg: '#0000aa', fg: '#ffffff', bold: true },
  tabActiveBg: { bg: '#0000aa', fg: '#ffffff', bold: true },
  tabBadge:    { bg: '#ffff00', fg: '#000000', bold: true },
  chipActive:  { bg: '#0000aa', fg: '#ffffff', bold: true },
  chipInactive:{ fg: '#aaaaaa' },
  chipDismissible: { bg: '#222222', fg: '#00ffff' },
  modalBackdrop:   { bg: '#000000' },
  modalBorder:     { fg: '#00ffff', bold: true },
  languageBar: { fg: '#00ffff', bold: true },
  activity:    { fg: '#00ff00', bold: true },
  trending:    { fg: '#ff00ff', bold: true },
  unread:      { fg: '#ffff00', bold: true },
  muted:       { fg: '#aaaaaa' },
  tabBar:      { fg: '#aaaaaa' },
  tabBarActive:{ fg: '#00ffff', bold: true, underline: true },
  inputBox:    { bg: '#000033', fg: '#ffffff', bold: true, underline: true },
  inputPrompt: { fg: '#00ffff', bold: true },
  cardLabel:   { fg: '#aaaaaa' },
  cardValue:   { fg: '#ffffff', bold: true },
  breadcrumb:  { fg: '#aaaaaa' },
  breadcrumbSep: { fg: '#555555' },
  breadcrumbActive: { fg: '#00ffff', bold: true },
  welcomeTitle:{ fg: '#00ffff', bold: true },
  welcomeAccent:{ fg: '#ffff00', bold: true },
  keyHint:     { fg: '#00ffff', bold: true },
  keyHintBracket:{ fg: '#aaaaaa' },
  rateOk:      { fg: '#00ff00', bold: true },
  rateWarn:    { fg: '#ffff00', bold: true },
  rateCrit:    { fg: '#ff4444', bold: true },
  toastInfo:   { bg: '#000033', fg: '#00ffff', bold: true },
  toastSuccess:{ bg: '#003300', fg: '#00ff00', bold: true },
  toastError:  { bg: '#330000', fg: '#ff4444', bold: true },
  toastWarning:{ bg: '#333300', fg: '#ffff00', bold: true },
  sectionHeading: { fg: '#ffffff', bold: true, underline: true },
  repoName:    { fg: '#ffffff' },
  repoNameSelected: { fg: '#00ffff', bold: true },
  statValue:   { fg: '#ffffff', bold: true },
  date:        { fg: '#aaaaaa' },
  packageName: { fg: '#ffffff', bold: true },
  packageSize: { fg: '#aaaaaa' },
  packageTag:  { fg: '#00ffff', bold: true },
  downloadCount:{ fg: '#aaaaaa' },
  pinned:      { fg: '#ffff00', bold: true },
  bookmarked:  { fg: '#ff00ff', bold: true },
  cardBorder:  { fg: '#555555' },
  cardBorderFocused: { fg: '#00ffff', bold: true },
  listItem:    { fg: '#ffffff' },
  listItemDim: { fg: '#aaaaaa' },
  emptyIcon:   { fg: '#00ffff', bold: true },
  emptyTitle:  { fg: '#ffffff', bold: true },
  emptyMessage:{ fg: '#aaaaaa' },
  heatmapLow:  { fg: '#004400' },
  heatmapMid:  { fg: '#00aa00', bold: true },
  heatmapHigh: { fg: '#00ff00', bold: true },
  traffic:     { fg: '#00ffff', bold: true },
  milestone:   { fg: '#ffff00', bold: true },
  label:       { fg: '#ff00ff', bold: true },
});

// ── Dracula — deep charcoal, vivid purple/pink/green ──────────────
const DRACULA = makeTheme({
  title:       { fg: P.dr_fg,     bold: true },
  heading:     { fg: P.dr_purple, bold: true },
  dim:         { fg: P.dr_comment },
  accent:      { fg: P.dr_purple },
  star:        { fg: P.dr_yellow },
  fork:        { fg: P.dr_cyan },
  issue:       { fg: P.dr_pink },
  pr:          { fg: P.dr_green },
  release:     { fg: P.dr_green },
  success:     { fg: P.dr_green },
  warning:     { fg: P.dr_orange },
  error:       { fg: P.dr_red },
  info:        { fg: P.dr_cyan },
  selection:   { bg: P.dr_sel,    fg: P.dr_fg,   bold: true },
  selectionDim:{ bg: '#3d3f4f',   fg: P.dr_comment },
  header:      { fg: P.dr_purple, bold: true, underline: true },
  statusBar:   { bg: P.dr_chrome, fg: P.dr_comment },
  chrome:      { bg: P.dr_chrome, fg: P.dr_fg },
  chromeAccent:{ bg: P.dr_chrome, fg: P.dr_purple, bold: true },
  tabInactive: { fg: P.dr_comment },
  tabActive:   { bg: P.dr_purple, fg: P.dr_bg,   bold: true },
  tabActiveBg: { bg: P.dr_purple, fg: P.dr_bg,   bold: true },
  tabBadge:    { bg: P.dr_orange, fg: P.dr_bg,   bold: true },
  chipActive:  { bg: P.dr_purple, fg: P.dr_bg,   bold: true },
  chipInactive:{ fg: P.dr_comment },
  chipDismissible: { bg: P.dr_sel, fg: P.dr_purple },
  modalBackdrop:   { bg: P.dr_chrome },
  modalBorder:     { fg: P.dr_purple, bold: true },
  languageBar: { fg: P.dr_pink },
  activity:    { fg: P.dr_green },
  trending:    { fg: P.dr_orange },
  unread:      { fg: P.dr_pink,   bold: true },
  muted:       { fg: P.dr_comment },
  tabBar:      { fg: P.dr_comment },
  tabBarActive:{ fg: P.dr_purple, bold: true, underline: true },
  inputBox:    { bg: P.dr_chrome, fg: P.dr_pink,  underline: true },
  inputPrompt: { fg: P.dr_pink,   bold: true },
  cardLabel:   { fg: P.dr_comment },
  cardValue:   { fg: P.dr_fg,     bold: true },
  breadcrumb:  { fg: P.dr_comment },
  breadcrumbSep:{ fg: '#44475a' },
  breadcrumbActive: { fg: P.dr_purple, bold: true },
  welcomeTitle:{ fg: P.dr_purple, bold: true },
  welcomeAccent:{ fg: P.dr_pink },
  keyHint:     { fg: P.dr_purple, bold: true },
  keyHintBracket:{ fg: P.dr_comment },
  rateOk:      { fg: P.dr_green },
  rateWarn:    { fg: P.dr_orange },
  rateCrit:    { fg: P.dr_red },
  toastInfo:   { bg: P.dr_sel,    fg: P.dr_purple, bold: true },
  toastSuccess:{ bg: '#1e3a28',   fg: P.dr_green,  bold: true },
  toastError:  { bg: '#3a1e1e',   fg: P.dr_red,    bold: true },
  toastWarning:{ bg: '#3a2e1e',   fg: P.dr_orange, bold: true },
  sectionHeading: { fg: P.dr_purple, bold: true },
  repoName:    { fg: P.dr_fg },
  repoNameSelected: { fg: P.dr_purple, bold: true },
  statValue:   { fg: P.dr_fg,     bold: true },
  date:        { fg: P.dr_comment },
  packageName: { fg: P.dr_cyan },
  packageSize: { fg: P.dr_comment },
  packageTag:  { fg: P.dr_green },
  downloadCount:{ fg: P.dr_comment },
  pinned:      { fg: P.dr_yellow, bold: true },
  bookmarked:  { fg: P.dr_green },
  cardBorder:  { fg: P.dr_sel },
  cardBorderFocused: { fg: P.dr_purple, bold: true },
  listItem:    { fg: P.dr_fg },
  listItemDim: { fg: P.dr_comment },
  emptyIcon:   { fg: P.dr_purple },
  emptyTitle:  { fg: P.dr_fg,     bold: true },
  emptyMessage:{ fg: P.dr_comment },
  heatmapLow:  { fg: '#1e3a28' },
  heatmapMid:  { fg: P.dr_green },
  heatmapHigh: { fg: '#50fa7b', bold: true },
  traffic:     { fg: P.dr_cyan },
  milestone:   { fg: P.dr_yellow },
  label:       { fg: P.dr_pink },
});

// ── Solarized Dark — warm muted, scholarly palette ────────────────
const SOLARIZED = makeTheme({
  title:       { fg: P.sol_base2,  bold: true },
  heading:     { fg: P.sol_yellow, bold: true },
  dim:         { fg: P.sol_base01 },
  accent:      { fg: P.sol_blue },
  star:        { fg: P.sol_yellow },
  fork:        { fg: P.sol_cyan },
  issue:       { fg: P.sol_orange },
  pr:          { fg: P.sol_blue },
  release:     { fg: P.sol_green },
  success:     { fg: P.sol_green },
  warning:     { fg: P.sol_yellow },
  error:       { fg: P.sol_red },
  info:        { fg: P.sol_cyan },
  selection:   { bg: P.sol_blue,   fg: P.sol_base3, bold: true },
  selectionDim:{ bg: P.sol_base02, fg: P.sol_base0 },
  header:      { fg: P.sol_yellow, bold: true, underline: true },
  statusBar:   { bg: P.sol_base02, fg: P.sol_base01 },
  chrome:      { bg: P.sol_base02, fg: P.sol_base1 },
  chromeAccent:{ bg: P.sol_base02, fg: P.sol_blue, bold: true },
  tabInactive: { fg: P.sol_base01 },
  tabActive:   { bg: P.sol_blue,   fg: P.sol_base3, bold: true },
  tabActiveBg: { bg: P.sol_blue,   fg: P.sol_base3, bold: true },
  tabBadge:    { bg: P.sol_yellow, fg: P.sol_base03, bold: true },
  chipActive:  { bg: P.sol_blue,   fg: P.sol_base3, bold: true },
  chipInactive:{ fg: P.sol_base01 },
  chipDismissible: { bg: P.sol_base02, fg: P.sol_blue },
  modalBackdrop:   { bg: P.sol_base03 },
  modalBorder:     { fg: P.sol_blue,  bold: true },
  languageBar: { fg: P.sol_cyan },
  activity:    { fg: P.sol_green },
  trending:    { fg: P.sol_magenta },
  unread:      { fg: P.sol_orange, bold: true },
  muted:       { fg: P.sol_base01 },
  tabBar:      { fg: P.sol_base01 },
  tabBarActive:{ fg: P.sol_yellow, bold: true, underline: true },
  inputBox:    { bg: P.sol_base02, fg: P.sol_blue, underline: true },
  inputPrompt: { fg: P.sol_yellow, bold: true },
  cardLabel:   { fg: P.sol_base01 },
  cardValue:   { fg: P.sol_base2,  bold: true },
  breadcrumb:  { fg: P.sol_base01 },
  breadcrumbSep:{ fg: P.sol_base02 },
  breadcrumbActive: { fg: P.sol_blue, bold: true },
  welcomeTitle:{ fg: P.sol_yellow, bold: true },
  welcomeAccent:{ fg: P.sol_orange },
  keyHint:     { fg: P.sol_cyan,  bold: true },
  keyHintBracket:{ fg: P.sol_base01 },
  rateOk:      { fg: P.sol_green },
  rateWarn:    { fg: P.sol_yellow },
  rateCrit:    { fg: P.sol_red },
  toastInfo:   { bg: P.sol_base02, fg: P.sol_blue,    bold: true },
  toastSuccess:{ bg: P.sol_base02, fg: P.sol_green,   bold: true },
  toastError:  { bg: P.sol_base02, fg: P.sol_red,     bold: true },
  toastWarning:{ bg: P.sol_base02, fg: P.sol_yellow,  bold: true },
  sectionHeading: { fg: P.sol_blue, bold: true },
  repoName:    { fg: P.sol_base1 },
  repoNameSelected: { fg: P.sol_blue, bold: true },
  statValue:   { fg: P.sol_base2,  bold: true },
  date:        { fg: P.sol_base01 },
  packageName: { fg: P.sol_cyan },
  packageSize: { fg: P.sol_base01 },
  packageTag:  { fg: P.sol_yellow },
  downloadCount:{ fg: P.sol_base01 },
  pinned:      { fg: P.sol_yellow, bold: true },
  bookmarked:  { fg: P.sol_violet },
  cardBorder:  { fg: P.sol_base02 },
  cardBorderFocused: { fg: P.sol_blue, bold: true },
  listItem:    { fg: P.sol_base1 },
  listItemDim: { fg: P.sol_base01 },
  emptyIcon:   { fg: P.sol_cyan },
  emptyTitle:  { fg: P.sol_base2,  bold: true },
  emptyMessage:{ fg: P.sol_base01 },
  heatmapLow:  { fg: P.sol_base02 },
  heatmapMid:  { fg: P.sol_green },
  heatmapHigh: { fg: P.sol_green,  bold: true },
  traffic:     { fg: P.sol_cyan },
  milestone:   { fg: P.sol_yellow },
  label:       { fg: P.sol_magenta },
});

// ── Nord — icy arctic palette ──────────────────────────────────────
const NORD = makeTheme({
  title:       { fg: P.nord6,  bold: true },
  heading:     { fg: P.nord8,  bold: true },
  dim:         { fg: P.nord3 },
  accent:      { fg: P.nord8 },
  star:        { fg: P.nord13 },
  fork:        { fg: P.nord7 },
  issue:       { fg: P.nord13 },
  pr:          { fg: P.nord9 },
  release:     { fg: P.nord14 },
  success:     { fg: P.nord14 },
  warning:     { fg: P.nord13 },
  error:       { fg: P.nord11 },
  info:        { fg: P.nord8 },
  selection:   { bg: P.nord10,  fg: P.nord6,  bold: true },
  selectionDim:{ bg: P.nord1,   fg: P.nord4 },
  header:      { fg: P.nord8,   bold: true, underline: true },
  statusBar:   { bg: P.nord1,   fg: P.nord3 },
  chrome:      { bg: P.nord0,   fg: P.nord4 },
  chromeAccent:{ bg: P.nord0,   fg: P.nord8,  bold: true },
  tabInactive: { fg: P.nord3 },
  tabActive:   { bg: P.nord10,  fg: P.nord6,  bold: true },
  tabActiveBg: { bg: P.nord10,  fg: P.nord6,  bold: true },
  tabBadge:    { bg: P.nord13,  fg: P.nord0,  bold: true },
  chipActive:  { bg: P.nord10,  fg: P.nord6,  bold: true },
  chipInactive:{ fg: P.nord3 },
  chipDismissible: { bg: P.nord1, fg: P.nord8 },
  modalBackdrop:   { bg: P.nord0 },
  modalBorder:     { fg: P.nord8, bold: true },
  languageBar: { fg: P.nord7 },
  activity:    { fg: P.nord14 },
  trending:    { fg: P.nord15 },
  unread:      { fg: P.nord13, bold: true },
  muted:       { fg: P.nord3 },
  tabBar:      { fg: P.nord3 },
  tabBarActive:{ fg: P.nord8,   bold: true, underline: true },
  inputBox:    { bg: P.nord1,   fg: P.nord8,  underline: true },
  inputPrompt: { fg: P.nord8,   bold: true },
  cardLabel:   { fg: P.nord3 },
  cardValue:   { fg: P.nord6,   bold: true },
  breadcrumb:  { fg: P.nord3 },
  breadcrumbSep:{ fg: P.nord2 },
  breadcrumbActive: { fg: P.nord8, bold: true },
  welcomeTitle:{ fg: P.nord8,   bold: true },
  welcomeAccent:{ fg: P.nord13 },
  keyHint:     { fg: P.nord8,   bold: true },
  keyHintBracket:{ fg: P.nord3 },
  rateOk:      { fg: P.nord14 },
  rateWarn:    { fg: P.nord13 },
  rateCrit:    { fg: P.nord11 },
  toastInfo:   { bg: P.nord1,   fg: P.nord8,  bold: true },
  toastSuccess:{ bg: '#1a2e1e', fg: P.nord14, bold: true },
  toastError:  { bg: '#2e1a1a', fg: P.nord11, bold: true },
  toastWarning:{ bg: '#2e2a1a', fg: P.nord13, bold: true },
  sectionHeading: { fg: P.nord8, bold: true },
  repoName:    { fg: P.nord4 },
  repoNameSelected: { fg: P.nord8, bold: true },
  statValue:   { fg: P.nord6,   bold: true },
  date:        { fg: P.nord3 },
  packageName: { fg: P.nord7 },
  packageSize: { fg: P.nord3 },
  packageTag:  { fg: P.nord8 },
  downloadCount:{ fg: P.nord3 },
  pinned:      { fg: P.nord13, bold: true },
  bookmarked:  { fg: P.nord15 },
  cardBorder:  { fg: P.nord2 },
  cardBorderFocused: { fg: P.nord8, bold: true },
  listItem:    { fg: P.nord4 },
  listItemDim: { fg: P.nord3 },
  emptyIcon:   { fg: P.nord7 },
  emptyTitle:  { fg: P.nord6,   bold: true },
  emptyMessage:{ fg: P.nord3 },
  heatmapLow:  { fg: P.nord2 },
  heatmapMid:  { fg: P.nord14 },
  heatmapHigh: { fg: P.nord14, bold: true },
  traffic:     { fg: P.nord7 },
  milestone:   { fg: P.nord13 },
  label:       { fg: P.nord15 },
});

// ── Monokai — vivid code-editor palette ───────────────────────────
const MONOKAI = makeTheme({
  title:       { fg: P.mk_fg,     bold: true },
  heading:     { fg: P.mk_green,  bold: true },
  dim:         { fg: P.mk_comment },
  accent:      { fg: P.mk_yellow },
  star:        { fg: P.mk_yellow },
  fork:        { fg: P.mk_blue },
  issue:       { fg: P.mk_red },
  pr:          { fg: P.mk_purple },
  release:     { fg: P.mk_green },
  success:     { fg: P.mk_green },
  warning:     { fg: P.mk_orange },
  error:       { fg: P.mk_red },
  info:        { fg: P.mk_blue },
  selection:   { bg: P.mk_sel,    fg: P.mk_fg,   bold: true },
  selectionDim:{ bg: '#35342d',   fg: P.mk_comment },
  header:      { fg: P.mk_green,  bold: true, underline: true },
  statusBar:   { bg: P.mk_chrome, fg: P.mk_comment },
  chrome:      { bg: P.mk_chrome, fg: P.mk_fg },
  chromeAccent:{ bg: P.mk_chrome, fg: P.mk_yellow, bold: true },
  tabInactive: { fg: P.mk_comment },
  tabActive:   { bg: P.mk_yellow, fg: P.mk_bg,   bold: true },
  tabActiveBg: { bg: P.mk_yellow, fg: P.mk_bg,   bold: true },
  tabBadge:    { bg: P.mk_red,    fg: P.mk_fg,   bold: true },
  chipActive:  { bg: P.mk_yellow, fg: P.mk_bg,   bold: true },
  chipInactive:{ fg: P.mk_comment },
  chipDismissible: { bg: P.mk_sel, fg: P.mk_yellow },
  modalBackdrop:   { bg: P.mk_chrome },
  modalBorder:     { fg: P.mk_yellow, bold: true },
  languageBar: { fg: P.mk_red },
  activity:    { fg: P.mk_green },
  trending:    { fg: P.mk_orange },
  unread:      { fg: P.mk_orange, bold: true },
  muted:       { fg: P.mk_comment },
  tabBar:      { fg: P.mk_comment },
  tabBarActive:{ fg: P.mk_yellow, bold: true, underline: true },
  inputBox:    { bg: P.mk_chrome, fg: P.mk_yellow, underline: true },
  inputPrompt: { fg: P.mk_orange, bold: true },
  cardLabel:   { fg: P.mk_comment },
  cardValue:   { fg: P.mk_fg,     bold: true },
  breadcrumb:  { fg: P.mk_comment },
  breadcrumbSep:{ fg: P.mk_sel },
  breadcrumbActive: { fg: P.mk_yellow, bold: true },
  welcomeTitle:{ fg: P.mk_green,  bold: true },
  welcomeAccent:{ fg: P.mk_orange },
  keyHint:     { fg: P.mk_yellow, bold: true },
  keyHintBracket:{ fg: P.mk_comment },
  rateOk:      { fg: P.mk_green },
  rateWarn:    { fg: P.mk_orange },
  rateCrit:    { fg: P.mk_red },
  toastInfo:   { bg: P.mk_sel,    fg: P.mk_blue,   bold: true },
  toastSuccess:{ bg: '#1e3a1e',   fg: P.mk_green,  bold: true },
  toastError:  { bg: '#3a1e1e',   fg: P.mk_red,    bold: true },
  toastWarning:{ bg: '#3a2e1e',   fg: P.mk_orange, bold: true },
  sectionHeading: { fg: P.mk_green, bold: true },
  repoName:    { fg: P.mk_fg },
  repoNameSelected: { fg: P.mk_yellow, bold: true },
  statValue:   { fg: P.mk_fg,     bold: true },
  date:        { fg: P.mk_comment },
  packageName: { fg: P.mk_blue },
  packageSize: { fg: P.mk_comment },
  packageTag:  { fg: P.mk_green },
  downloadCount:{ fg: P.mk_comment },
  pinned:      { fg: P.mk_yellow, bold: true },
  bookmarked:  { fg: P.mk_purple },
  cardBorder:  { fg: P.mk_sel },
  cardBorderFocused: { fg: P.mk_yellow, bold: true },
  listItem:    { fg: P.mk_fg },
  listItemDim: { fg: P.mk_comment },
  emptyIcon:   { fg: P.mk_blue },
  emptyTitle:  { fg: P.mk_fg,     bold: true },
  emptyMessage:{ fg: P.mk_comment },
  heatmapLow:  { fg: '#1e2d1e' },
  heatmapMid:  { fg: P.mk_green },
  heatmapHigh: { fg: '#a6e22e', bold: true },
  traffic:     { fg: P.mk_blue },
  milestone:   { fg: P.mk_orange },
  label:       { fg: P.mk_red },
});

// ── Gruvbox Dark Hard — warm earth, retro-terminal ────────────────
const GRUVBOX = makeTheme({
  title:       { fg: P.gb_fg0,    bold: true },
  heading:     { fg: P.gb_yellowB, bold: true },
  dim:         { fg: P.gb_bg4 },
  accent:      { fg: P.gb_blueB },
  star:        { fg: P.gb_yellowB },
  fork:        { fg: P.gb_aquaB },
  issue:       { fg: P.gb_orangeB },
  pr:          { fg: P.gb_blueB },
  release:     { fg: P.gb_greenB },
  success:     { fg: P.gb_greenB },
  warning:     { fg: P.gb_yellowB },
  error:       { fg: P.gb_redB },
  info:        { fg: P.gb_blueB },
  selection:   { bg: P.gb_bg2,    fg: P.gb_fg0,  bold: true },
  selectionDim:{ bg: P.gb_bg1,    fg: P.gb_fg3 },
  header:      { fg: P.gb_yellowB, bold: true, underline: true },
  statusBar:   { bg: P.gb_bg1,    fg: P.gb_bg4 },
  chrome:      { bg: P.gb_bg0h,   fg: P.gb_fg1 },
  chromeAccent:{ bg: P.gb_bg0h,   fg: P.gb_yellowB, bold: true },
  tabInactive: { fg: P.gb_bg4 },
  tabActive:   { bg: P.gb_yellowB, fg: P.gb_bg0h, bold: true },
  tabActiveBg: { bg: P.gb_yellowB, fg: P.gb_bg0h, bold: true },
  tabBadge:    { bg: P.gb_orangeB, fg: P.gb_bg0h, bold: true },
  chipActive:  { bg: P.gb_yellowB, fg: P.gb_bg0h, bold: true },
  chipInactive:{ fg: P.gb_bg4 },
  chipDismissible: { bg: P.gb_bg1, fg: P.gb_yellowB },
  modalBackdrop:   { bg: P.gb_bg0h },
  modalBorder:     { fg: P.gb_yellowB, bold: true },
  languageBar: { fg: P.gb_aquaB },
  activity:    { fg: P.gb_greenB },
  trending:    { fg: P.gb_orangeB },
  unread:      { fg: P.gb_orangeB, bold: true },
  muted:       { fg: P.gb_bg4 },
  tabBar:      { fg: P.gb_bg4 },
  tabBarActive:{ fg: P.gb_yellowB, bold: true, underline: true },
  inputBox:    { bg: P.gb_bg1,    fg: P.gb_yellowB, underline: true },
  inputPrompt: { fg: P.gb_orangeB, bold: true },
  cardLabel:   { fg: P.gb_bg4 },
  cardValue:   { fg: P.gb_fg0,    bold: true },
  breadcrumb:  { fg: P.gb_bg4 },
  breadcrumbSep:{ fg: P.gb_bg2 },
  breadcrumbActive: { fg: P.gb_yellowB, bold: true },
  welcomeTitle:{ fg: P.gb_yellowB, bold: true },
  welcomeAccent:{ fg: P.gb_orangeB },
  keyHint:     { fg: P.gb_yellowB, bold: true },
  keyHintBracket:{ fg: P.gb_bg4 },
  rateOk:      { fg: P.gb_greenB },
  rateWarn:    { fg: P.gb_yellowB },
  rateCrit:    { fg: P.gb_redB },
  toastInfo:   { bg: P.gb_bg1,    fg: P.gb_blueB,   bold: true },
  toastSuccess:{ bg: '#1e2a1e',   fg: P.gb_greenB,  bold: true },
  toastError:  { bg: '#2a1e1e',   fg: P.gb_redB,    bold: true },
  toastWarning:{ bg: '#2a261e',   fg: P.gb_yellowB, bold: true },
  sectionHeading: { fg: P.gb_yellowB, bold: true },
  repoName:    { fg: P.gb_fg1 },
  repoNameSelected: { fg: P.gb_yellowB, bold: true },
  statValue:   { fg: P.gb_fg0,    bold: true },
  date:        { fg: P.gb_bg4 },
  packageName: { fg: P.gb_aquaB },
  packageSize: { fg: P.gb_bg4 },
  packageTag:  { fg: P.gb_greenB },
  downloadCount:{ fg: P.gb_bg4 },
  pinned:      { fg: P.gb_yellowB, bold: true },
  bookmarked:  { fg: P.gb_purpleB },
  cardBorder:  { fg: P.gb_bg2 },
  cardBorderFocused: { fg: P.gb_yellowB, bold: true },
  listItem:    { fg: P.gb_fg1 },
  listItemDim: { fg: P.gb_bg4 },
  emptyIcon:   { fg: P.gb_aquaB },
  emptyTitle:  { fg: P.gb_fg0,    bold: true },
  emptyMessage:{ fg: P.gb_bg4 },
  heatmapLow:  { fg: P.gb_bg2 },
  heatmapMid:  { fg: P.gb_greenB },
  heatmapHigh: { fg: P.gb_greenB, bold: true },
  traffic:     { fg: P.gb_blueB },
  milestone:   { fg: P.gb_yellowB },
  label:       { fg: P.gb_purpleB },
});

// ── Light — GitHub light, daylight-optimised ──────────────────────
const LIGHT = makeTheme({
  title:       { fg: P.lt_fg,     bold: true },
  heading:     { fg: P.lt_teal,   bold: true },
  dim:         { fg: P.lt_fgDim },
  accent:      { fg: P.lt_teal },
  star:        { fg: P.lt_orange },
  fork:        { fg: P.lt_teal },
  issue:       { fg: P.lt_orange },
  pr:          { fg: P.lt_blue },
  release:     { fg: P.lt_green },
  success:     { fg: P.lt_green },
  warning:     { fg: P.lt_orange },
  error:       { fg: P.lt_red },
  info:        { fg: P.lt_blue },
  selection:   { bg: P.lt_sel,    fg: '#ffffff', bold: true },
  selectionDim:{ bg: P.lt_border, fg: P.lt_fg },
  header:      { fg: P.lt_fg,     bold: true, underline: true },
  statusBar:   { bg: P.lt_bg2,    fg: P.lt_fgDim },
  chrome:      { bg: P.lt_bg2,    fg: P.lt_fg },
  chromeAccent:{ bg: P.lt_bg2,    fg: P.lt_teal, bold: true },
  tabInactive: { fg: P.lt_fgDim },
  tabActive:   { bg: P.lt_sel,    fg: '#ffffff', bold: true },
  tabActiveBg: { bg: P.lt_sel,    fg: '#ffffff', bold: true },
  tabBadge:    { bg: P.lt_orange, fg: '#ffffff', bold: true },
  chipActive:  { bg: P.lt_sel,    fg: '#ffffff', bold: true },
  chipInactive:{ fg: P.lt_fgDim },
  chipDismissible: { bg: P.lt_bg2, fg: P.lt_teal },
  modalBackdrop:   { bg: P.lt_border },
  modalBorder:     { fg: P.lt_teal, bold: true },
  languageBar: { fg: P.lt_blue },
  activity:    { fg: P.lt_green },
  trending:    { fg: P.lt_purple },
  unread:      { fg: P.lt_orange, bold: true },
  muted:       { fg: P.lt_fgDim },
  tabBar:      { fg: P.lt_fgDim },
  tabBarActive:{ fg: P.lt_teal,   bold: true, underline: true },
  inputBox:    { bg: '#f0f3f6',   fg: P.lt_teal, underline: true },
  inputPrompt: { fg: P.lt_teal,   bold: true },
  cardLabel:   { fg: P.lt_fgDim },
  cardValue:   { fg: P.lt_fg,     bold: true },
  breadcrumb:  { fg: P.lt_fgDim },
  breadcrumbSep:{ fg: P.lt_border },
  breadcrumbActive: { fg: P.lt_teal, bold: true },
  welcomeTitle:{ fg: P.lt_teal,   bold: true },
  welcomeAccent:{ fg: P.lt_orange },
  keyHint:     { fg: P.lt_teal,   bold: true },
  keyHintBracket:{ fg: P.lt_fgDim },
  rateOk:      { fg: P.lt_green },
  rateWarn:    { fg: P.lt_orange },
  rateCrit:    { fg: P.lt_red },
  toastInfo:   { bg: '#ddf4ff',   fg: P.lt_blue,   bold: true },
  toastSuccess:{ bg: '#dcffe4',   fg: P.lt_green,  bold: true },
  toastError:  { bg: '#ffebe9',   fg: P.lt_red,    bold: true },
  toastWarning:{ bg: '#fff8c5',   fg: P.lt_orange, bold: true },
  sectionHeading: { fg: P.lt_teal, bold: true },
  repoName:    { fg: P.lt_fg },
  repoNameSelected: { fg: P.lt_teal, bold: true },
  statValue:   { fg: P.lt_fg,     bold: true },
  date:        { fg: P.lt_fgDim },
  packageName: { fg: P.lt_blue },
  packageSize: { fg: P.lt_fgDim },
  packageTag:  { fg: P.lt_teal },
  downloadCount:{ fg: P.lt_fgDim },
  pinned:      { fg: P.lt_orange, bold: true },
  bookmarked:  { fg: P.lt_purple },
  cardBorder:  { fg: P.lt_border },
  cardBorderFocused: { fg: P.lt_teal, bold: true },
  listItem:    { fg: P.lt_fg },
  listItemDim: { fg: P.lt_fgDim },
  emptyIcon:   { fg: P.lt_teal },
  emptyTitle:  { fg: P.lt_fg,     bold: true },
  emptyMessage:{ fg: P.lt_fgDim },
  heatmapLow:  { fg: '#d0e9c0' },
  heatmapMid:  { fg: P.lt_green },
  heatmapHigh: { fg: '#1a7f37', bold: true },
  traffic:     { fg: P.lt_blue },
  milestone:   { fg: P.lt_orange },
  label:       { fg: P.lt_purple },
});

// ── Ayu Dark — deep blue/orange IDE palette ───────────────────────
const AYU = makeTheme({
  title:       { fg: P.ayu_fg,    bold: true },
  heading:     { fg: P.ayu_orange, bold: true },
  dim:         { fg: P.ayu_fgDim },
  accent:      { fg: P.ayu_blue },
  star:        { fg: P.ayu_yellow },
  fork:        { fg: P.ayu_cyan },
  issue:       { fg: P.ayu_orange },
  pr:          { fg: P.ayu_blue },
  release:     { fg: P.ayu_green },
  success:     { fg: P.ayu_green },
  warning:     { fg: P.ayu_yellow },
  error:       { fg: P.ayu_red },
  info:        { fg: P.ayu_cyan },
  selection:   { bg: P.ayu_sel,   fg: P.ayu_fg,  bold: true },
  selectionDim:{ bg: P.ayu_ui,    fg: P.ayu_fgDim },
  header:      { fg: P.ayu_orange, bold: true, underline: true },
  statusBar:   { bg: P.ayu_bg2,   fg: P.ayu_fgDim },
  chrome:      { bg: P.ayu_bg2,   fg: P.ayu_fg },
  chromeAccent:{ bg: P.ayu_bg2,   fg: P.ayu_orange, bold: true },
  tabInactive: { fg: P.ayu_fgDim },
  tabActive:   { bg: P.ayu_orange, fg: P.ayu_bg, bold: true },
  tabActiveBg: { bg: P.ayu_orange, fg: P.ayu_bg, bold: true },
  tabBadge:    { bg: P.ayu_yellow, fg: P.ayu_bg, bold: true },
  chipActive:  { bg: P.ayu_orange, fg: P.ayu_bg, bold: true },
  chipInactive:{ fg: P.ayu_fgDim },
  chipDismissible: { bg: P.ayu_ui, fg: P.ayu_orange },
  modalBackdrop:   { bg: P.ayu_bg2 },
  modalBorder:     { fg: P.ayu_orange, bold: true },
  languageBar: { fg: P.ayu_cyan },
  activity:    { fg: P.ayu_green },
  trending:    { fg: P.ayu_purple },
  unread:      { fg: P.ayu_yellow, bold: true },
  muted:       { fg: P.ayu_fgDim },
  tabBar:      { fg: P.ayu_fgDim },
  tabBarActive:{ fg: P.ayu_orange, bold: true, underline: true },
  inputBox:    { bg: P.ayu_bg2,   fg: P.ayu_orange, underline: true },
  inputPrompt: { fg: P.ayu_orange, bold: true },
  cardLabel:   { fg: P.ayu_fgDim },
  cardValue:   { fg: P.ayu_fg,    bold: true },
  breadcrumb:  { fg: P.ayu_fgDim },
  breadcrumbSep:{ fg: P.ayu_ui },
  breadcrumbActive: { fg: P.ayu_orange, bold: true },
  welcomeTitle:{ fg: P.ayu_orange, bold: true },
  welcomeAccent:{ fg: P.ayu_yellow },
  keyHint:     { fg: P.ayu_orange, bold: true },
  keyHintBracket:{ fg: P.ayu_fgDim },
  rateOk:      { fg: P.ayu_green },
  rateWarn:    { fg: P.ayu_yellow },
  rateCrit:    { fg: P.ayu_red },
  toastInfo:   { bg: P.ayu_ui,    fg: P.ayu_cyan,   bold: true },
  toastSuccess:{ bg: '#1a2e1e',   fg: P.ayu_green,  bold: true },
  toastError:  { bg: '#2e1a1a',   fg: P.ayu_red,    bold: true },
  toastWarning:{ bg: '#2e281a',   fg: P.ayu_yellow, bold: true },
  sectionHeading: { fg: P.ayu_orange, bold: true },
  repoName:    { fg: P.ayu_fg },
  repoNameSelected: { fg: P.ayu_orange, bold: true },
  statValue:   { fg: P.ayu_fg,    bold: true },
  date:        { fg: P.ayu_fgDim },
  packageName: { fg: P.ayu_cyan },
  packageSize: { fg: P.ayu_fgDim },
  packageTag:  { fg: P.ayu_green },
  downloadCount:{ fg: P.ayu_fgDim },
  pinned:      { fg: P.ayu_yellow, bold: true },
  bookmarked:  { fg: P.ayu_purple },
  cardBorder:  { fg: P.ayu_ui },
  cardBorderFocused: { fg: P.ayu_orange, bold: true },
  listItem:    { fg: P.ayu_fg },
  listItemDim: { fg: P.ayu_fgDim },
  emptyIcon:   { fg: P.ayu_cyan },
  emptyTitle:  { fg: P.ayu_fg,    bold: true },
  emptyMessage:{ fg: P.ayu_fgDim },
  heatmapLow:  { fg: '#1a2e1a' },
  heatmapMid:  { fg: P.ayu_green },
  heatmapHigh: { fg: '#7fd962', bold: true },
  traffic:     { fg: P.ayu_cyan },
  milestone:   { fg: P.ayu_yellow },
  label:       { fg: P.ayu_purple },
});

// ── Catppuccin Mocha — soft pastel lavender/rose on deep slate ────
const CATPPUCCIN = makeTheme({
  title:       { fg: P.cat_text,    bold: true },
  heading:     { fg: P.cat_mauve,   bold: true },
  dim:         { fg: P.cat_overlay1 },
  accent:      { fg: P.cat_blue },
  star:        { fg: P.cat_yellow },
  fork:        { fg: P.cat_teal },
  issue:       { fg: P.cat_peach },
  pr:          { fg: P.cat_sapphire },
  release:     { fg: P.cat_green },
  success:     { fg: P.cat_green },
  warning:     { fg: P.cat_yellow },
  error:       { fg: P.cat_red },
  info:        { fg: P.cat_sky },
  selection:   { bg: P.cat_surface1, fg: P.cat_text, bold: true },
  selectionDim:{ bg: P.cat_surface0, fg: P.cat_subtext0 },
  header:      { fg: P.cat_mauve,   bold: true, underline: true },
  statusBar:   { bg: P.cat_mantle,  fg: P.cat_overlay2 },
  chrome:      { bg: P.cat_crust,   fg: P.cat_text },
  chromeAccent:{ bg: P.cat_crust,   fg: P.cat_mauve, bold: true },
  tabInactive: { fg: P.cat_overlay1 },
  tabActive:   { bg: P.cat_mauve,   fg: P.cat_base, bold: true },
  tabActiveBg: { bg: P.cat_mauve,   fg: P.cat_base, bold: true },
  tabBadge:    { bg: P.cat_peach,   fg: P.cat_base, bold: true },
  chipActive:  { bg: P.cat_mauve,   fg: P.cat_base, bold: true },
  chipInactive:{ fg: P.cat_overlay1 },
  chipDismissible: { bg: P.cat_surface0, fg: P.cat_mauve },
  modalBackdrop:   { bg: P.cat_crust },
  modalBorder:     { fg: P.cat_mauve, bold: true },
  languageBar: { fg: P.cat_sky },
  activity:    { fg: P.cat_green },
  trending:    { fg: P.cat_pink },
  unread:      { fg: P.cat_peach,   bold: true },
  muted:       { fg: P.cat_overlay1 },
  tabBar:      { fg: P.cat_overlay1 },
  tabBarActive:{ fg: P.cat_mauve,   bold: true, underline: true },
  inputBox:    { bg: P.cat_surface0, fg: P.cat_mauve, underline: true },
  inputPrompt: { fg: P.cat_mauve,   bold: true },
  cardLabel:   { fg: P.cat_overlay1 },
  cardValue:   { fg: P.cat_text,    bold: true },
  breadcrumb:  { fg: P.cat_overlay1 },
  breadcrumbSep:{ fg: P.cat_surface2 },
  breadcrumbActive: { fg: P.cat_mauve, bold: true },
  welcomeTitle:{ fg: P.cat_mauve,   bold: true },
  welcomeAccent:{ fg: P.cat_peach },
  keyHint:     { fg: P.cat_mauve,   bold: true },
  keyHintBracket:{ fg: P.cat_overlay1 },
  rateOk:      { fg: P.cat_green },
  rateWarn:    { fg: P.cat_yellow },
  rateCrit:    { fg: P.cat_red },
  toastInfo:   { bg: P.cat_surface0, fg: P.cat_blue,  bold: true },
  toastSuccess:{ bg: '#1e2e1e',     fg: P.cat_green,  bold: true },
  toastError:  { bg: '#2e1e1e',     fg: P.cat_red,    bold: true },
  toastWarning:{ bg: '#2e2a1e',     fg: P.cat_yellow, bold: true },
  sectionHeading: { fg: P.cat_mauve, bold: true },
  repoName:    { fg: P.cat_text },
  repoNameSelected: { fg: P.cat_mauve, bold: true },
  statValue:   { fg: P.cat_text,    bold: true },
  date:        { fg: P.cat_overlay1 },
  packageName: { fg: P.cat_sky },
  packageSize: { fg: P.cat_overlay1 },
  packageTag:  { fg: P.cat_teal },
  downloadCount:{ fg: P.cat_overlay1 },
  pinned:      { fg: P.cat_yellow,  bold: true },
  bookmarked:  { fg: P.cat_pink },
  cardBorder:  { fg: P.cat_surface2 },
  cardBorderFocused: { fg: P.cat_mauve, bold: true },
  listItem:    { fg: P.cat_text },
  listItemDim: { fg: P.cat_overlay1 },
  emptyIcon:   { fg: P.cat_teal },
  emptyTitle:  { fg: P.cat_text,    bold: true },
  emptyMessage:{ fg: P.cat_overlay1 },
  heatmapLow:  { fg: P.cat_surface2 },
  heatmapMid:  { fg: P.cat_green },
  heatmapHigh: { fg: '#a6e3a1', bold: true },
  traffic:     { fg: P.cat_sapphire },
  milestone:   { fg: P.cat_yellow },
  label:       { fg: P.cat_pink },
});

// ── Theme registry ────────────────────────────────────────────────
const THEMES = {
  default:      DEFAULT,
  highContrast: HIGH_CONTRAST,
  dracula:      DRACULA,
  solarized:    SOLARIZED,
  nord:         NORD,
  monokai:      MONOKAI,
  gruvbox:      GRUVBOX,
  light:        LIGHT,
  ayu:          AYU,
  catppuccin:   CATPPUCCIN,
};

let active = 'default';
// NO_COLOR is imported from config.mjs — single source of truth

export function listThemes() { return Object.keys(THEMES); }
export function getThemeName() { return active; }

export function setTheme(name) {
  if (!THEMES[name]) return false;
  active = name;
  appState.themeName = name;
  try { writeFileSync(THEME_FILE, name); } catch {}
  return true;
}

export function loadTheme() {
  try {
    if (existsSync(THEME_FILE)) {
      const name = readFileSync(THEME_FILE, 'utf-8').trim();
      if (THEMES[name]) active = name;
    }
  } catch {}
  return active;
}

export function color(role) {
  if (NO_COLOR) return null;
  return THEMES[active][role] ?? null;
}
