// Self-tests for tools/check-imports.mjs.
//
// Strategy: the tool reads from a hardcoded ROOT = dirname(script)/.., which
// points at the real project. To test the tool's logic without touching the
// real project, we shell out to `node tools/check-imports.mjs` and verify:
//   (1) clean state → exit 0, "0 issues"
//   (2) broken state → exit 1, mentions the right file+symbol
//   (3) restore from break → exit 0 again
//
// We simulate "broken" state by writing a temp .mjs file into the tree
// that the tool's file-crawler will pick up. The tool walks the project root
// and excludes `tests/`, `node_modules/`, `tools/`, `.git` — so any file we
// drop elsewhere in the tree gets audited. We drop fixtures into tui/ (which
// IS audited), then rm them on teardown. Every fixture has a `try/finally`
// to guarantee cleanup even on assertion failure.

import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { spawnSync } from 'node:child_process';
import { writeFileSync, unlinkSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOOL = join(ROOT, 'tools', 'check-imports.mjs');

function runTool() {
  return spawnSync(process.execPath, [TOOL], {
    cwd: ROOT,
    encoding: 'utf8',
    timeout: 30000,
  });
}

// Drop a fixture file and return a teardown function. The fixture is placed
// in `tui/` (audited) with a recognisable name so teardown is reliable.
function fixture(name, body) {
  const path = join(ROOT, 'tui', name);
  writeFileSync(path, body);
  return () => { try { unlinkSync(path); } catch {} };
}

// ── Test: clean baseline ──────────────────────────────────────────────
test('check-imports: clean codebase reports 0 issues', () => {
  const result = runTool();
  assert.equal(result.status, 0, `expected exit 0, got ${result.status}\n${result.stderr}`);
  assert.match(result.stdout, /0 issues/);
});

// ── Test: dropped fixture with unbound reference is detected ──────────
test('check-imports: catches unbound reference to state.mjs export', () => {
  // Reference `showMessage` and `confirm` (both exported from state.mjs)
  // without importing them. Tool should flag both names.
  const teardown = fixture('_check_imports_fixture.mjs', [
    '// Auto-generated by tests/check-imports.test.mjs — DO NOT EDIT.',
    'export function fixtureFn() {',
    '  showMessage("hi", "info");',
    '  confirm("ok", () => {}, "label");',
    '}',
    '',
  ].join('\n'));
  try {
    const result = runTool();
    assert.equal(result.status, 1, `expected exit 1, got ${result.status}\n${result.stderr}`);
    assert.match(result.stderr, /_check_imports_fixture\.mjs/);
    assert.match(result.stderr, /showMessage/);
    assert.match(result.stderr, /confirm/);
  } finally {
    teardown();
  }
});

// ── Test: dropped fixture that DOES import everything — no flag ────────
test('check-imports: no flag when fixture imports the symbol it uses', () => {
  const teardown = fixture('_check_imports_clean.mjs', [
    '// Auto-generated by tests/check-imports.test.mjs — DO NOT EDIT.',
    'import { showMessage } from "./state.mjs";',
    'export function fixtureFn() {',
    '  showMessage("hi", "info");',
    '}',
    '',
  ].join('\n'));
  try {
    const result = runTool();
    assert.ok(
      !result.stderr.includes('_check_imports_clean.mjs'),
      `fixture should not be flagged but got: ${result.stderr}`,
    );
  } finally {
    teardown();
  }
});

// ── Test: typeof defensive check is classified correctly ───────────────
test('check-imports: typeof X defensive check is NOT flagged as a real bug', () => {
  // Use `confirm` (state.mjs export) only inside a typeof check — never
  // call it directly. Tool should NOT classify it as an unbound use.
  const teardown = fixture('_check_imports_typeof.mjs', [
    '// Auto-generated by tests/check-imports.test.mjs — DO NOT EDIT.',
    'if (typeof confirm === "function") {}',
    '',
  ].join('\n'));
  try {
    const result = runTool();
    const stderr = result.stderr;
    assert.ok(
      !stderr.includes('uses `confirm` from tui/state.mjs'),
      `defensive typeof should not be reported as unbound use, got: ${stderr}`,
    );
  } finally {
    teardown();
  }
});

// ── Test: class method definitions are not flagged ─────────────────────
test('check-imports: class method `render() {` is not flagged', () => {
  // `render` is exported from state.mjs. A class method called `render()`
  // should NOT be flagged as a free reference — it's bound to `this`.
  const teardown = fixture('_check_imports_class.mjs', [
    '// Auto-generated by tests/check-imports.test.mjs — DO NOT EDIT.',
    'export class MyView {',
    '  render() {',
    '    return null;',
    '  }',
    '}',
    '',
  ].join('\n'));
  try {
    const result = runTool();
    assert.ok(
      !result.stderr.includes('_check_imports_class.mjs'),
      `class method render() should not be flagged, got: ${result.stderr}`,
    );
  } finally {
    teardown();
  }
});